export const Users = [
  {
    id:1,
    profilePicture: "assets/person/1.jpeg",
    username: "Safak Kocaoglu",
  },
  {
    id:2,
    profilePicture: "assets/person/2.jpeg",
    username: "Janell Shrum",
  },
  {
    id:3,
    profilePicture: "assets/person/3.jpeg",
    username: "Alex Durden",
  },
  {
    id:4,
    profilePicture: "assets/person/4.jpeg",
    username: "Dora Hawks",
  },
  {
    id:5,
    profilePicture: "assets/person/5.jpeg",
    username: "Thomas Holden",
  },
  {
    id:6,
    profilePicture: "assets/person/6.jpeg",
    username: "Shirley Beauchamp",
  },
  {
    id:7,
    profilePicture: "assets/person/7.jpeg",
    username: "Travis Bennett",
  },
  {
    id:8,
    profilePicture: "assets/person/8.jpeg",
    username: "Kristen Thomas",
  },
  {
    id:9,
    profilePicture: "assets/person/9.jpeg",
    username: "Gary Duty",
  },
  {
    id:10,
    profilePicture: "assets/person/10.jpeg",
    username: "Safak Kocaoglu",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "https://www.signupgenius.com/cms/images/nonprofit/community-service-ideas.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "https://www.harlemworldmagazine.com/wp-content/uploads/2018/12/get-involved-in-parks-harlem-600x348.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "https://www.nycfoodpolicy.org/wp-content/uploads/2018/07/new-york-city-community-gardening-coalition-2012-cgimageoptim.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "https://www.cityofmalden.org/ImageRepository/Document?documentID=3469",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "https://biketothesea.org/wp-content/uploads/2013/09/Garden6-1024x768.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "https://www.nycgovparks.org/sub_about/parks_history/gardens/images/no_neg_num_Green_Thumb_Program_undated_lg.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "https://rockyripple.in.gov/wp-content/uploads/2020/02/03302012-002-1024x768.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "https://www.unidosus.org/wp-content/uploads/2015/06/CommunityGarden_384.png",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "https://i.guim.co.uk/img/media/57d54f2801b6dbbda1e9a3ebbdb61b4863a0451d/0_161_4928_2957/master/4928.jpg?width=1200&height=900&quality=85&auto=format&fit=crop&s=bfb9446f2a66fc910a414c44b74ec72d",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "https://media.timeout.com/images/103362195/image.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];